### ISSUE TITLE
Errors on go build

### ISSUE THREAD

**Issue by tomleb** [ewhal/nyaa#42] opened 2017-05-05 02:44 UTC
22:42 $ go build
 _/home/tomleb/dev/go/nyaa
./main.go:224: cannot use "" (type string) as type Navigation in field value
./main.go:224: cannot use "" (type string) as type *url.URL in field value
./main.go:224: cannot use 1 (type int) as type *mux.Route in field value
./main.go:224: too many values in struct initializer
./main.go:226: undefined: templates in templates.ExecuteTemplate
./main.go:285: undefined: singleapiHandler
./models.go:210: t.Status undefined (type *Torrents has no field or method Status)

After a clean go get github.com/ewhal/nyaa.

**Comment by kipukun** [comment] 2017-05-05 02:58
Duplicate of #40.

**Closed** 2017-05-05 05:53 UTC
